name: Build Maven Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 15
        uses: actions/setup-java@v4
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get mvn modules
        run: |
          ./mvnw dependency:resolve-plugins dependency:resolve dependency:go-offline

      - name: Copy artifacts
        run: |
          cp -R ~/.m2 ./m2

      - name: Build Docker image
        run: docker build --build-arg MAVEN_CACHE_DIR=~/.m2/repository -t my-maven-verify .
